name: mobile_app_roject
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.0.0
  flame_tiled: ^2.0.2
  animated_splash_screen: ^1.3.0 
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.5
  fluttertoast: ^8.2.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Main Characters/Male Character/
    - assets/fonts/
    - assets/images/
    - assets/tiles/
    - assets/Terrain/
    - assets/images/Main Characters/Female Character/
    - assets/images/Main Characters/Virtual Guy/
    - assets/images/HUD/

  fonts:
    - family: PixelFont
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
