// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo2DXaAj_5UU24Kx_nRROSrjKD44nqCN0',
    appId: '1:309713315529:web:5c7c07bbfc332b3eae8f18',
    messagingSenderId: '309713315529',
    projectId: 'gamedb-8ce60',
    authDomain: 'gamedb-8ce60.firebaseapp.com',
    storageBucket: 'gamedb-8ce60.firebasestorage.app',
    measurementId: 'G-DHP4RQ00SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsZv9UuSyE721_oi2-NjokSnlQgnwDl88',
    appId: '1:309713315529:android:997df82d7f5c36bcae8f18',
    messagingSenderId: '309713315529',
    projectId: 'gamedb-8ce60',
    storageBucket: 'gamedb-8ce60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWN3prDJL75aIldMHcKdgstbX44BQ1_vw',
    appId: '1:309713315529:ios:94904bf50cb692eaae8f18',
    messagingSenderId: '309713315529',
    projectId: 'gamedb-8ce60',
    storageBucket: 'gamedb-8ce60.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWN3prDJL75aIldMHcKdgstbX44BQ1_vw',
    appId: '1:309713315529:ios:94904bf50cb692eaae8f18',
    messagingSenderId: '309713315529',
    projectId: 'gamedb-8ce60',
    storageBucket: 'gamedb-8ce60.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo2DXaAj_5UU24Kx_nRROSrjKD44nqCN0',
    appId: '1:309713315529:web:c930b5ddae5283acae8f18',
    messagingSenderId: '309713315529',
    projectId: 'gamedb-8ce60',
    authDomain: 'gamedb-8ce60.firebaseapp.com',
    storageBucket: 'gamedb-8ce60.firebasestorage.app',
    measurementId: 'G-925RNQ2LQS',
  );

}